ExampleGridLayout:

#:set s dp(150)

<ExampleGridLayout@GridLayout>:
    cols: 3
    canvas:
        Rectangle:
            pos: self.center_x-s/2, self.center_y-s/2
            size: s, s
        Line:
            # points: (0, 0, 100, 100, 200, 0, 300, 100)
            points: (0,0,self.width/4,100,self.width/2, 0, self.width*3/4, 100, self.width, 0)
            width: 2
        Ellipse:
            pos: self.center_x-s*1.5, self.center_y-s/2
            size: s, s/2
